- name: Install software
  apt:
    name:
      - nginx-core
      - nginx-common
      - brotli
      - nginx
      - nginx-full
      - certbot
      - python3-certbot-nginx
    state: present
  tags:
    - configuration
    - nginx

- name: Create common root
  file:
    path: /var/www/common
    state: directory
    owner: www-data
    group: www-data
  register: nginx_default_root
  tags:
    - configuration
    - nginx

- name: Setup Nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf
  tags:
    - configuration
    - nginx

- name: Setup default site config
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-available/default
  register: nginx_default_site
  tags:
    - configuration
    - nginx

- name: Enable default site
  file:
    state: link
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
  register: nginx_default_enabled
  tags:
    - configuration
    - nginx

- name: Setup proxy params
  template:
    src: templates/proxy_params.j2
    dest: /etc/nginx/proxy_params
  register: nginx_proxy_params
  tags:
    - configuration
    - nginx

- name: Reload config
  service:
    name: nginx
    state: reloaded
  when: |
    nginx_default_root.changed or
    nginx_conf.changed or
    nginx_default_site.changed or
    nginx_default_enabled.changed or
    nginx_proxy_params.changed
  tags:
    - configuration
    - nginx

- name: Setup server index
  template:
    src: templates/index.html.j2
    dest: /var/www/common/index.html
  tags:
    - configuration
    - nginx
