- name: Add APT repositories
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - ppa:nginx/stable
    - ppa:hda-me/nginx-stable
    - ppa:certbot/certbot
  register: nginx_repos

- name: Update APT caches
  apt:
    update_cache: yes
  when: nginx_repos.changed

- name: Install software
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - nginx
    - brotli
    - nginx-module-brotli
    - nginx-module-pagespeed
    - python-certbot-nginx

- name: Create common root
  file:
    path: /var/www/common
    state: directory
    owner: www-data
    group: www-data
  register: nginx_default_root

- name: Setup Nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf

- name: Setup default site config
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-available/default.conf
  register: nginx_default_site

- name: Enable default site
  file:
    state: link
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default.conf
  register: nginx_default_enabled

- name: Setup proxy params
  template:
    src: templates/proxy_params.j2
    dest: /etc/nginx/proxy_params
  register: nginx_proxy_params

- name: Reload config
  service:
    name: nginx
    state: reloaded
  when: |
    nginx_default_root.changed or
    nginx_conf.changed or
    nginx_default_site.changed or
    nginx_default_enabled.changed or
    nginx_proxy_params.changed

- name: Setup server index
  template:
    src: templates/index.html.j2
    dest: /var/www/common/index.html
