- name: Ensure certificate directory exists
  file:
    path: /usr/local/share/ca-certificates/Yandex
    state: directory
  tags:
    - configuration
    - yandex-cloud

- name: Check Yandex certificate
  stat:
    path: /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt
  register: yandex_crt_result
  tags:
    - configuration
    - yandex-cloud

- name: Setup Yandex certificate
  get_url:
    url: https://storage.yandexcloud.net/cloud-certs/CA.pem
    dest: /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt
  when: yandex_crt_result.stat.exists == False
  tags:
    - configuration
    - yandex-cloud

- name: Check YC tool
  stat:
    path: /root/yandex-cloud/bin/yc
  register: yc_cli
  tags:
    - configuration
    - yandex-cloud

- name: Install YC tool
  shell:
    cmd: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  when: yc_cli.stat.exists == False
  tags:
    - configuration
    - yandex-cloud
