- name: Create notifier script
  template:
    src: templates/notifier.j2
    dest: /usr/local/bin/notify-login
    mode: 0755
  tags:
    - configuration
    - login-notify

- name: Create PAM hook
  template:
    src: templates/pam.d.notify-login.j2
    dest: /etc/pam.d/notify-login
  tags:
    - configuration
    - login-notify

- name: Include hook to /etc/pam.d/common-session
  lineinfile:
    dest: /etc/pam.d/common-session
    line: '@include notify-login'
    state: present
    create: yes
  tags:
    - configuration
    - login-notify

- name: Include hook to /etc/pam.d/common-session-noninteractive
  lineinfile:
    dest: /etc/pam.d/common-session-noninteractive
    line: '@include notify-login'
    state: present
    create: yes
  tags:
    - configuration
    - login-notify
