# Base infrastructure setup
- hosts: base
  become: yes
  become_method: sudo

  roles:
    - system
    - firewall
    - login-notify
    - postfix
    - fail2ban
    - docker
    - nginx
    - nodejs
    - monitoring
    - logrotate
