- hosts: dante_proxy
  become: true
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - system
    - firewall
    - logrotate
    - dante
    - fail2ban
    - reboot
