- hosts: docker_web
  become: true
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - system
    - yandex-cloud
    - firewall
    - fail2ban
    - docker
    - nginx
    - logrotate
