- hosts: playground
  become: yes
  become_method: sudo

  roles:
    - system
    - firewall
    - login-notify
    - postfix
    - fail2ban
    - docker
    - nginx
    - nodejs
    - mongo
    - monitoring
    - monitoring-mongo
    - logrotate
    - deploy-users
