# Setup for web proxies in Armenia
- hosts: proxy_am
  become: yes
  become_method: sudo

  roles:
    - system
    - login-notify
    - firewall
    - postfix
    - logrotate
    - proxy
    - fail2ban
