- name: Create MongoDB data directory
  file:
    name: /docker_data/{{ mongo_name }}
    state: directory

- name: Run MongoDB in Docker
  docker_container:
    name: '{{ mongo_name }}'
    image: mongo:latest
    published_ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /docker_data/{{ mongo_name }}/db:/data/db
      - /docker_data/{{ mongo_name }}/configdb:/data/configdb

- name: Install Python driver
  pip:
    name: '{{ item }}'
  with_items:
    - pymongo
