- name: Setup locale ru_RU.UTF-8
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Setup timezone
  timezone:
    name: UTC

- name: Update APT caches
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic software
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - zsh
    - git
    - curl
    - tmux
    - mosh
    - htop
    - python-pip
    - python-virtualenv
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - build-essential

- name: Disallow login as root
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin no'
    state: present
  register: disallow_ssh_root

- name: Reload SSH
  service:
    name: ssh
    state: reloaded
  when: disallow_ssh_root.changed
