- name: Setup locale ru_RU.UTF-8
  locale_gen:
    name: ru_RU.UTF-8
    state: present
  tags:
    - configuration
    - system
    - locale

- name: Setup timezone
  timezone:
    name: UTC
  tags:
    - configuration
    - system
    - timezone

- name: Update APT caches
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - configuration
    - system
    - basic-software

- name: Install basic software
  apt:
    name:
      - aptitude
      - zsh
      - git
      - curl
      - tmux
      - mosh
      - htop
      - python-pip
      - python-virtualenv
      - python-apt
      - python3
      - python3-pip
      - python3-virtualenv
      - python3-apt
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - build-essential
    state: present
  tags:
    - configuration
    - system
    - basic-software

- name: Disallow login as root
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin no'
    state: present
  register: disallow_ssh_root
  tags:
    - configuration
    - system
    - ssh

- name: Reload SSH
  service:
    name: ssh
    state: reloaded
  when: disallow_ssh_root.changed
  tags:
    - configuration
    - system
    - ssh
