- name: Install basic software
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - zsh
      - git
      - curl
      - tmux
      - mosh
      - htop
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - build-essential
    state: present
  tags:
    - configuration
    - system
    - basic-software
