- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow services
  ufw:
    rule: '{{ item.rule }}'
    proto: '{{ item.proto }}'
    to_port: '{{ item.to_port }}'
  with_items: '{{ allowed_services }}'

- name: Enable firewall
  ufw:
    state: enabled
    policy: reject

- name: Start firewall service
  service:
    name: ufw
    state: started
