- name: Create deploy users
  user:
    name: '{{ item.name }}'
    password: "{{ lookup('password', '.secrets/ssh/{{ http_domain }}/{{ item.name }}/password length=128') }}"
    update_password: on_create
    home: '{{ item.home }}'
    move_home: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
  with_items: '{{ deploy_users }}'
  tags:
    - configuration
    - deploy-users

- name: Download private keys
  fetch:
    src: '{{ item.home }}/.ssh/id_rsa'
    dest: '.secrets/ssh/{{ http_domain }}/{{ item.name }}/id_rsa'
    flat: yes
  with_items: '{{ deploy_users }}'
  tags:
    - configuration
    - deploy-users

- name: Download public keys
  fetch:
    src: '{{ item.home }}/.ssh/id_rsa.pub'
    dest: '.secrets/ssh/{{ http_domain }}/{{ item.name }}/id_rsa.pub'
    flat: yes
  with_items: '{{ deploy_users }}'
  tags:
    - configuration
    - deploy-users

- name: Setup SSH auth
  copy:
    src: '{{ item.home }}/.ssh/id_rsa.pub'
    dest: '{{ item.home }}/.ssh/authorized_keys'
    remote_src: yes
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: 0600
  with_items: '{{ deploy_users }}'
  tags:
    - configuration
    - deploy-users
