- name: Create deploy users
  user:
    name: '{{ item.name }}'
    password: "{{ lookup('password', '/tmp/passwordfile length=40') }}"
    update_password: on_create
    home: '{{ item.home }}'
    move_home: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
  with_items: '{{ deploy_users }}'

- name: Download private keys
  fetch:
    src: '{{ item.home }}/.ssh/id_rsa'
    dest: '~/.private/deploy/{{ http_domain }}/{{ item.name }}/id_rsa'
    flat: yes
  with_items: '{{ deploy_users }}'

- name: Download public keys
  fetch:
    src: '{{ item.home }}/.ssh/id_rsa.pub'
    dest: '~/.private/deploy/{{ http_domain }}/{{ item.name }}/id_rsa.pub'
    flat: yes
  with_items: '{{ deploy_users }}'

- name: Check deploy key in vault
  local_action: stat path='~/.private/deploy/{{ http_domain }}/{{ item.name }}/id_rsa.pub'
  ignore_errors: yes
  become: no
  with_items: '{{ deploy_users }}'
  register: deploy_key_results

