- name: Install requirements
  apt:
    name:
      - golang-go
      - python3-passlib
      - libpam-pwdfile
    state: present
  tags:
    - configuration
    - dumbproxy

- name: Copy dumbproxy sources
  copy:
    src: dumbproxy
    dest: '/opt/src'
  register: dumbproxy_new_sources
  tags:
    - configuration
    - dumbproxy

- name: Check dumbproxy binary
  stat:
    path: '/opt/src/dumbproxy/dumbproxy'
  register: dumbproxy_binary_stat
  tags:
    - configuration
    - dumbproxy

- name: Build dumbproxy
  shell:
    cmd: go build -a -buildvcs=false
    chdir: '/opt/src/dumbproxy'
  register: dumbproxy_new_build
  when: dumbproxy_new_sources.changed or dumbproxy_binary_stat.stat.exists == False
  tags:
    - configuration
    - dumbproxy

- name: Create dumbproxy bin link
  file:
    src: '/opt/src/dumbproxy/dumbproxy'
    dest: '/usr/local/bin/dumbproxy'
    state: link
  tags:
    - configuration
    - dumbproxy

- name: Generate /etc/default/dumbproxy
  template:
    src: 'templates/etc_default_dumbproxy.j2'
    dest: '/etc/default/dumbproxy'
  register: dumbproxy_new_config
  tags:
    - configuration
    - dumbproxy

- name: Setup dumbproxy users
  htpasswd:
    path: /etc/dumbproxy.htpasswd
    name: '{{ item.name }}'
    password: '{{ item.password | string }}'
  loop: '{{ proxy_users }}'
  register: dumbproxy_new_users
  tags:
    - configuration
    - dumbproxy

- name: Create dumbproxy systemd config
  template:
    src: templates/dumbproxy.service.j2
    dest: /etc/systemd/system/dumbproxy.service
  register: dumbproxy_systemd_config
  tags:
    - configuration
    - dumbproxy

- name: Reload systemd
  shell:
    cmd: systemctl daemon-reload
  when: dumbproxy_systemd_config.changed
  tags:
    - configuration
    - dumbproxy

- name: Start dumbproxy
  systemd:
    name: dumbproxy
    state: started
    enabled: true
  tags:
    - configuration
    - dumbproxy

- name: Restart dumbproxy
  systemd:
    name: dumbproxy
    state: restarted
  when: dumbproxy_new_config.changed or dumbproxy_new_users.changed or dumbproxy_new_build.changed
  tags:
    - configuration
    - dumbproxy

- name: Initialize proxy certs
  shell:
    cmd: curl -o /dev/null -s -w '%{http_code}' 'https://{{ http_domain }}' | tee /tmp/status.txt | grep 407
  when: dumbproxy_new_config.changed or dumbproxy_new_build.changed
  tags:
    - configuration
    - dumbproxy

- name: Create dumbproxy-log-monitor dirs
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - /opt/dumbproxy-log-monitor/bin
    - /opt/dumbproxy-log-monitor/etc
    - /opt/dumbproxy-log-monitor/var
    - /opt/dumbproxy-log-monitor/data
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Check that obsolete files are absent
  file:
    name: '{{ item }}'
    state: absent
  with_items:
    - /opt/dumbproxy-log-monitor/var/main.db
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Download dumbproxy-log-monitor bundle
  get_url:
    url: 'https://github.com/andre487/dumbproxy-log-monitor/releases/download/{{ dumbproxy_log_monitor_version }}/dumbproxy-log-monitor-linux-x86_64.tar.gz'
    dest: /opt/dumbproxy-log-monitor/data/bundle.tar.gz
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Unpack dumbproxy-log-monitor bundle
  unarchive:
    src: /opt/dumbproxy-log-monitor/data/bundle.tar.gz
    remote_src: true
    dest: /opt/dumbproxy-log-monitor/bin
  register: unpack_dumbproxy_log_monitor
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Create dumbproxy-log-monitor secrets
  copy:
    content: '{{ item.content }}'
    dest: '/opt/dumbproxy-log-monitor/etc/{{ item.path }}'
    mode: 0600
  with_items:
    - path: mailer.json
      content: '{{ mailer_config_json }}'
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Create dumbproxy-log-monitor systemd config
  template:
    src: templates/dumbproxy-log-monitor.service.j2
    dest: /etc/systemd/system/dumbproxy-log-monitor.service
  register: dumbproxy_monitor_systemd_config
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Reload systemd
  shell:
    cmd: systemctl daemon-reload
  when: dumbproxy_monitor_systemd_config.changed
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Start dumbproxy-log-monitor
  systemd:
    name: dumbproxy-log-monitor
    state: started
    enabled: true
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor

- name: Restart dumbproxy-log-monitor
  systemd:
    name: dumbproxy-log-monitor
    state: restarted
    enabled: true
  when: dumbproxy_monitor_systemd_config.changed or unpack_dumbproxy_log_monitor.changed
  tags:
    - configuration
    - dumbproxy
    - dumbproxy-log-monitor
