- name: Add APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: docker_key
  tags:
    - configuration
    - docker

- name: Add repository
  apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
      state: present
  register: docker_repo
  tags:
    - configuration
    - docker

- name: Update APT caches
  apt:
    update_cache: yes
  when: docker_key.changed or docker_repo.changed
  tags:
    - configuration
    - docker

- name: Install basic Python packages
  pip:
    name:
      - docker

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
  tags:
    - configuration
    - docker

- name: Check Docker Compose
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_result
  tags:
    - configuration
    - docker
    - docker-compose

- name: Install Docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: docker_compose_result.stat.exists == False
  tags:
    - configuration
    - docker
    - docker-compose

- name: Create data directory
  file:
    name: /docker_data
    state: directory
  tags:
    - configuration
    - docker

- name: Install docker-clean
  copy:
    src: data/docker-clean/docker-clean
    dest: /usr/local/bin/docker-clean
  tags:
    - configuration
    - docker

- name: Add main user to Docker group
  user:
    name: '{{ remote_user }}'
    groups:
      - '{{ remote_user }}'
      - docker
  tags:
    - configuration
    - docker
