- name: Add APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: docker_key

- name: Add repository
  apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
      state: present
  register: docker_repo

- name: Update APT caches
  apt:
    update_cache: yes
  when: docker_key.changed or docker_repo.changed

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Install Python package
  pip:
    name: docker-py

- name: Create data directory
  file:
    name: /docker_data
    state: directory

- name: Install docker-clean
  synchronize:
    src: data/docker-clean/docker-clean
    dest: /usr/local/bin/docker-clean
