- name: Add APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: docker_key
  tags:
    - configuration
    - docker

- name: Add repository
  apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
      state: present
  register: docker_repo
  tags:
    - configuration
    - docker

- name: Update APT caches
  apt:
    update_cache: yes
  when: docker_key.changed or docker_repo.changed
  tags:
    - configuration
    - docker

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - python3-docker
    state: present
  tags:
    - configuration
    - docker

- name: Create data directory
  file:
    name: /docker_data
    state: directory
  tags:
    - configuration
    - docker

- name: Install docker-clean
  copy:
    src: data/docker-clean/docker-clean
    dest: /usr/local/bin/docker-clean
    mode: 0755
  tags:
    - configuration
    - docker

- name: Add main user to Docker group
  user:
    name: '{{ remote_user }}'
    groups:
      - '{{ remote_user }}'
      - docker
  tags:
    - configuration
    - docker
