---
mongo_name: common-mongo

fail2ban_loglevel: 2
fail2ban_bantime: 86400
fail2ban_destemail: '{{ admin_email }}'
fail2ban_services:
  - name: sshd
    port: 22

deploy_users:
  - name: 'www-data'
    home: '/var/www'

allowed_services:
  - rule: limit
    proto: tcp
    to_port: 22
  - rule: limit
    proto: udp
    to_port: '60000:61000'
  - rule: allow
    proto: tcp
    to_port: 80
  - rule: allow
    proto: tcp
    to_port: 443
