- name: Create app dir
  file:
    path: '{{ project_path_ }}'
    state: directory
  tags:
    - deploy
    - docker-compose-project

- name: Create data dir
  file:
    path: '{{ mongo_db_path_ }}'
    state: directory
  tags:
    - deploy
    - docker-compose-project

- name: Setup docker compose config
  template:
    src: '{{ docker_compose_file_ }}'
    dest: '{{ project_path_ }}/docker-compose.yml'
  register: docker_compose
  tags:
    - deploy
    - docker-compose-project

- name: Install to SystemD
  template:
    src: templates/docker-compose.service.j2
    dest: /etc/systemd/system/docker-compose-{{ http_domain }}.service
  register: systemd_installation
  tags:
    - deploy
    - docker-compose-project

- name: Reload SystemD
  systemd_service:
    daemon_reload: true
  when: systemd_installation.changed
  tags:
    - deploy
    - docker-compose-project

- name: Docker YandexCloud login
  shell:
    executable: /bin/bash
    cmd: |
      set -eo pipefail
      iam_token="$(curl -H 'Metadata-Flavor: Google' 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token' | jq -r .access_token)"
      echo "$iam_token" | docker login --username iam --password-stdin cr.yandex
  when: docker_yandex_cloud_login_

- name: Update app
  shell:
    cmd: docker compose pull
    chdir: '{{ project_path_ }}'
  tags:
    - deploy
    - docker-compose-project

- name: Docker YandexCloud logout
  docker_login:
    state: absent
    registry_url: cr.yandex

- name: Enable and restart app
  systemd_service:
    name: docker-compose-{{ http_domain }}
    state: restarted
    enabled: true
  tags:
    - deploy
    - docker-compose-project

- name: Cleanup images
  shell:
    executable: /usr/bin/python3
    cmd: "{{ lookup('file', 'scripts/cleanup_docker_images.py') }}"
  tags:
    - deploy
    - docker-compose-project

- name: Docker clean
  shell:
    cmd: docker-clean
